name: vara
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  charts_flutter: ^0.9.0
  sqflite: ^1.3.1
  path: ^1.7.0
  path_provider: ^1.6.11
  file_picker: ^1.13.2
  excel: ^1.1.4
  http: ^0.12.2
  provider: ^4.3.2
  decimal: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
flutter_intl:
  enabled: true
